contact_links:
  - name: 💡 Feature Request
    url: https://github.com/ptarmiganlabs/butler-icon-upload/discussions/new
    about: Share ideas for new features
  - name: ❓ Question
    url: https://github.com/ptarmiganlabs/butler-icon-upload/discussions/new
    about: General questions
